import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  portfolio: defineTable({
    key: v.string(),
    content: v.any(),
    imageStorageId: v.optional(v.id("_storage")),
    imageDisplay2xStorageId: v.optional(v.id("_storage")),
    imageBlurStorageId: v.optional(v.id("_storage")),
    imageArchiveStorageId: v.optional(v.id("_storage")),
    updatedAt: v.number(),
    updatedBy: v.optional(v.string()),
  }).index("by_key", ["key"]),
  portfolioRevisions: defineTable({
    key: v.string(),
    content: v.any(),
    imageStorageId: v.optional(v.id("_storage")),
    imageDisplay2xStorageId: v.optional(v.id("_storage")),
    imageBlurStorageId: v.optional(v.id("_storage")),
    imageArchiveStorageId: v.optional(v.id("_storage")),
    kind: v.union(v.literal("save"), v.literal("image"), v.literal("rollback")),
    message: v.string(),
    createdAt: v.number(),
    createdBy: v.optional(v.string()),
    parentRevisionId: v.optional(v.id("portfolioRevisions")),
    restoredFromRevisionId: v.optional(v.id("portfolioRevisions")),
  }).index("by_key_and_createdAt", ["key", "createdAt"]),
  adminSessions: defineTable({
    token: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
  }).index("by_token", ["token"]),
  aiSettings: defineTable({
    key: v.string(),
    provider: v.string(),
    baseUrl: v.string(),
    defaultModel: v.string(),
    encryptedApiKey: v.optional(v.string()),
    apiKeyPreview: v.optional(v.string()),
    apiKeyRotatedAt: v.optional(v.number()),
    temperature: v.number(),
    maxOutputTokens: v.number(),
    dailyAnonymousMessageLimit: v.number(),
    dailyAdminMessageLimit: v.number(),
    monthlyTokenLimit: v.number(),
    enabledScopes: v.array(v.string()),
    enabledSkills: v.array(v.string()),
    isEnabled: v.boolean(),
    showPublicChat: v.boolean(),
    updatedAt: v.number(),
    updatedBy: v.optional(v.string()),
  }).index("by_key", ["key"]),
  aiChatThreads: defineTable({
    visitorKeyHash: v.string(),
    title: v.string(),
    threadSummary: v.string(),
    activeScopes: v.array(v.string()),
    activeEntities: v.array(v.string()),
    lastIntent: v.string(),
    lastToolResults: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_visitorKeyHash", ["visitorKeyHash"])
    .index("by_updatedAt", ["updatedAt"]),
  aiChatMessages: defineTable({
    threadId: v.id("aiChatThreads"),
    visitorKeyHash: v.string(),
    role: v.union(v.literal("user"), v.literal("assistant"), v.literal("system")),
    content: v.string(),
    model: v.optional(v.string()),
    provider: v.optional(v.string()),
    inputTokens: v.optional(v.number()),
    outputTokens: v.optional(v.number()),
    totalTokens: v.optional(v.number()),
    error: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_threadId_and_createdAt", ["threadId", "createdAt"])
    .index("by_visitorKeyHash_and_createdAt", ["visitorKeyHash", "createdAt"]),
  aiUsageEvents: defineTable({
    threadId: v.optional(v.id("aiChatThreads")),
    visitorKeyHash: v.string(),
    provider: v.string(),
    model: v.string(),
    inputTokens: v.number(),
    outputTokens: v.number(),
    status: v.union(v.literal("success"), v.literal("error"), v.literal("blocked")),
    createdAt: v.number(),
  })
    .index("by_visitorKeyHash_and_createdAt", ["visitorKeyHash", "createdAt"])
    .index("by_createdAt", ["createdAt"]),
  aiSettingsAuditEvents: defineTable({
    adminSessionTokenHash: v.string(),
    action: v.string(),
    safeDetails: v.string(),
    createdAt: v.number(),
  }).index("by_createdAt", ["createdAt"]),
});
